name: cicd

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos run format-check

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos exec -c 10 -- flutter analyze --fatal-infos
